version: '3.8'

services:
  # 前端应用
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - sdkwork-network

  # 后端 API 服务（示例配置）
  backend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:pass@db:5432/sdkwork
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - sdkwork-network

  # 数据库
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=sdkwork
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - sdkwork-network

  # Redis 缓存
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - sdkwork-network

volumes:
  postgres_data:

networks:
  sdkwork-network:
    driver: bridge