/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/account/wallet': RouteRecordInfo<'/account/wallet', '/account/wallet', Record<never, never>, Record<never, never>>,
    '/agent/create': RouteRecordInfo<'/agent/create', '/agent/create', Record<never, never>, Record<never, never>>,
    '/agent/profile': RouteRecordInfo<'/agent/profile', '/agent/profile', Record<never, never>, Record<never, never>>,
    '/agents': RouteRecordInfo<'/agents', '/agents', Record<never, never>, Record<never, never>>,
    '/ai-image-generator/': RouteRecordInfo<'/ai-image-generator/', '/ai-image-generator', Record<never, never>, Record<never, never>>,
    '/ai-music-generator/': RouteRecordInfo<'/ai-music-generator/', '/ai-music-generator', Record<never, never>, Record<never, never>>,
    '/ai-video-generator/': RouteRecordInfo<'/ai-video-generator/', '/ai-video-generator', Record<never, never>, Record<never, never>>,
    '/appointment/list': RouteRecordInfo<'/appointment/list', '/appointment/list', Record<never, never>, Record<never, never>>,
    '/audio/recorder': RouteRecordInfo<'/audio/recorder', '/audio/recorder', Record<never, never>, Record<never, never>>,
    '/auth/': RouteRecordInfo<'/auth/', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/forgot-password': RouteRecordInfo<'/auth/forgot-password', '/auth/forgot-password', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/register': RouteRecordInfo<'/auth/register', '/auth/register', Record<never, never>, Record<never, never>>,
    '/auth/reset-password': RouteRecordInfo<'/auth/reset-password', '/auth/reset-password', Record<never, never>, Record<never, never>>,
    '/chat/': RouteRecordInfo<'/chat/', '/chat', Record<never, never>, Record<never, never>>,
    '/chat/[id]': RouteRecordInfo<'/chat/[id]', '/chat/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/chat/profile/[id]': RouteRecordInfo<'/chat/profile/[id]', '/chat/profile/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/device/device-list': RouteRecordInfo<'/device/device-list', '/device/device-list', Record<never, never>, Record<never, never>>,
    '/error/404': RouteRecordInfo<'/error/404', '/error/404', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/home2': RouteRecordInfo<'/home2', '/home2', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/login/[method]': RouteRecordInfo<'/login/[method]', '/login/:method', { method: ParamValue<true> }, { method: ParamValue<false> }>,
    '/mall': RouteRecordInfo<'/mall', '/mall', Record<never, never>, Record<never, never>>,
    '/mpc/devices': RouteRecordInfo<'/mpc/devices', '/mpc/devices', Record<never, never>, Record<never, never>>,
    '/music/': RouteRecordInfo<'/music/', '/music', Record<never, never>, Record<never, never>>,
    '/music/[id]': RouteRecordInfo<'/music/[id]', '/music/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/music/list': RouteRecordInfo<'/music/list', '/music/list', Record<never, never>, Record<never, never>>,
    '/notifications': RouteRecordInfo<'/notifications', '/notifications', Record<never, never>, Record<never, never>>,
    '/product/[id]': RouteRecordInfo<'/product/[id]', '/product/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/product/list': RouteRecordInfo<'/product/list', '/product/list', Record<never, never>, Record<never, never>>,
    '/products': RouteRecordInfo<'/products', '/products', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/recorder': RouteRecordInfo<'/recorder', '/recorder', Record<never, never>, Record<never, never>>,
    '/slides-player-demo': RouteRecordInfo<'/slides-player-demo', '/slides-player-demo', Record<never, never>, Record<never, never>>,
    '/speech-to-text/': RouteRecordInfo<'/speech-to-text/', '/speech-to-text', Record<never, never>, Record<never, never>>,
    '/speech-to-text-demo': RouteRecordInfo<'/speech-to-text-demo', '/speech-to-text-demo', Record<never, never>, Record<never, never>>,
    '/subtitles-demo': RouteRecordInfo<'/subtitles-demo', '/subtitles-demo', Record<never, never>, Record<never, never>>,
    '/text-to-speech/': RouteRecordInfo<'/text-to-speech/', '/text-to-speech', Record<never, never>, Record<never, never>>,
    '/trade/order/[id]': RouteRecordInfo<'/trade/order/[id]', '/trade/order/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/trade/order/list': RouteRecordInfo<'/trade/order/list', '/trade/order/list', Record<never, never>, Record<never, never>>,
    '/trade/trade': RouteRecordInfo<'/trade/trade', '/trade/trade', Record<never, never>, Record<never, never>>,
    '/ui/audio-upload-demo': RouteRecordInfo<'/ui/audio-upload-demo', '/ui/audio-upload-demo', Record<never, never>, Record<never, never>>,
    '/ui/file-upload-demo': RouteRecordInfo<'/ui/file-upload-demo', '/ui/file-upload-demo', Record<never, never>, Record<never, never>>,
    '/ui/image-upload-demo': RouteRecordInfo<'/ui/image-upload-demo', '/ui/image-upload-demo', Record<never, never>, Record<never, never>>,
    '/ui/popup-demo': RouteRecordInfo<'/ui/popup-demo', '/ui/popup-demo', Record<never, never>, Record<never, never>>,
    '/ui/video-upload-demo': RouteRecordInfo<'/ui/video-upload-demo', '/ui/video-upload-demo', Record<never, never>, Record<never, never>>,
    '/user/favorites': RouteRecordInfo<'/user/favorites', '/user/favorites', Record<never, never>, Record<never, never>>,
    '/user/history': RouteRecordInfo<'/user/history', '/user/history', Record<never, never>, Record<never, never>>,
    '/user/profile': RouteRecordInfo<'/user/profile', '/user/profile', Record<never, never>, Record<never, never>>,
    '/user/user-center': RouteRecordInfo<'/user/user-center', '/user/user-center', Record<never, never>, Record<never, never>>,
    '/user-profile-demo': RouteRecordInfo<'/user-profile-demo', '/user-profile-demo', Record<never, never>, Record<never, never>>,
    '/video/': RouteRecordInfo<'/video/', '/video', Record<never, never>, Record<never, never>>,
    '/video/[id]': RouteRecordInfo<'/video/[id]', '/video/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/video-demo': RouteRecordInfo<'/video-demo', '/video-demo', Record<never, never>, Record<never, never>>,
    '/video-list-demo': RouteRecordInfo<'/video-list-demo', '/video-list-demo', Record<never, never>, Record<never, never>>,
    '/video-player-card-demo': RouteRecordInfo<'/video-player-card-demo', '/video-player-card-demo', Record<never, never>, Record<never, never>>,
    '/video-player-demo': RouteRecordInfo<'/video-player-demo', '/video-player-demo', Record<never, never>, Record<never, never>>,
    '/video-player-fullscreen-demo': RouteRecordInfo<'/video-player-fullscreen-demo', '/video-player-fullscreen-demo', Record<never, never>, Record<never, never>>,
    '/video-player-mini-demo': RouteRecordInfo<'/video-player-mini-demo', '/video-player-mini-demo', Record<never, never>, Record<never, never>>,
    '/video-player-theater-demo': RouteRecordInfo<'/video-player-theater-demo', '/video-player-theater-demo', Record<never, never>, Record<never, never>>,
    '/voice-list/': RouteRecordInfo<'/voice-list/', '/voice-list', Record<never, never>, Record<never, never>>,
    '/voice-list-popup/': RouteRecordInfo<'/voice-list-popup/', '/voice-list-popup', Record<never, never>, Record<never, never>>,
    '/waterfall-demo': RouteRecordInfo<'/waterfall-demo', '/waterfall-demo', Record<never, never>, Record<never, never>>,
  }
}
