export const ICONS:any = {
  AI: 'icon_ai.png',
  XLS: 'icon_excel.png',
  XLSX: 'icon_excel.png',
  JPG: 'icon_img.png',
  PNG: 'icon_img.png',
  JPEG: 'icon_img.png',
  GIF: 'icon_img.png',
  BMP: 'icon_img.png',
  SVG: 'icon_img.png',
  WEBP: 'icon_img.png',
  MP1: 'icon_music.png',
  MP2: 'icon_music.png',
  MP3: 'icon_music.png',
  M4A: 'icon_music.png',
  M3A: 'icon_music.png',
  WAV: 'icon_music.png',
  AIF: 'icon_music.png',
  AIFF: 'icon_music.png',
  MID: 'icon_music.png',
  RMI: 'icon_music.png',
  AU: 'icon_music.png',
  RA: 'icon_music.png',
  RAM: 'icon_music.png',
  PPT: 'icon_ppt.png',
  PPTX: 'icon_ppt.png',
  PDF: 'icon_pdf.png',
  PSD: 'icon_psd.png',
  MP4: 'icon_video.png',
  AVI: 'icon_video.png',
  MOV: 'icon_video.png',
  RMVB: 'icon_video.png',
  RM: 'icon_video.png',
  FLV: 'icon_video.png',
  M4V: 'icon_video.png',
  ASF: 'icon_video.png',
  DIVX: 'icon_video.png',
  MPG: 'icon_video.png',
  MPEG: 'icon_video.png',
  MPE: 'icon_video.png',
  WMV: 'icon_video.png',
  MKV: 'icon_video.png',
  VOB: 'icon_video.png',
  DOC: 'icon_word.png',
  DOCX: 'icon_word.png',
  LOG: 'icon_txt.png',
  CLASS: 'icon_txt.png',
  TXT: 'icon_txt.png',
  C: 'icon_txt.png',
  CPP: 'icon_txt.png',
  PY: 'icon_txt.png',
  JAVA: 'icon_txt.png',
  JS: 'icon_js.png',
  MD: 'icon_md.png',
  CSS: 'icon_css.png',
};
export const MIME_MAPPING:any = {
  ai: 'application/postscript',
  eps: 'application/postscript',
  exe: 'application/octet-stream',
  doc: 'application/vnd.ms-word',
  xls: 'application/vnd.ms-excel',
  ppt: 'application/vnd.ms-powerpoint',
  pps: 'application/vnd.ms-powerpoint',
  pdf: 'application/pdf',
  xml: 'application/xml',
  odt: 'application/vnd.oasis.opendocument.text',
  swf: 'application/x-shockwave-flash',

  //压缩文件类型的
  gz: 'application/x-gzip',
  tgz: 'application/x-gzip',
  bz: 'application/x-bzip2',
  bz2: 'application/x-bzip2',
  tbz: 'application/x-bzip2',
  zip: 'application/zip',
  rar: 'application/x-rar',
  tar: 'application/x-tar',
  '7z': 'application/x-7z-compressed',

  //文字类型
  txt: 'text/plain',
  php: 'text/x-php',
  html: 'text/html',
  htm: 'text/html',
  js: 'text/javascript',
  css: 'text/css',
  rtf: 'text/rtf',
  rtfd: 'text/rtfd',
  py: 'text/x-python',
  java: 'text/x-java-source',
  rb: 'text/x-ruby',
  sh: 'text/x-shellscript',
  pl: 'text/x-perl',
  sql: 'text/x-sql',

  //图片类型的
  bmp: 'image/x-ms-bmp',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  gif: 'image/gif',
  png: 'image/png',
  tif: 'image/tiff',
  tiff: 'image/tiff',
  tga: 'image/x-targa',
  psd: 'image/vnd.adobe.photoshop',

  //音频文件类型的
  mp3: 'audio/mpeg',
  mid: 'audio/midi',
  ogg: 'audio/ogg',
  mp4a: 'audio/mp4',
  wav: 'audio/wav',
  wma: 'audio/x-ms-wma',

  //视频文件类型的
  avi: 'video/x-msvideo',
  dv: 'video/x-dv',
  mp4: 'video/mp4',
  mpeg: 'video/mpeg',
  mpg: 'video/mpeg',
  mov: 'video/quicktime',
  wm: 'video/x-ms-wmv',
  flv: 'video/x-flv',
  mkv: 'video/x-matroska',
};

export const CODE_EXTENSIONS = [
  'java',
  'c',
  'vue',
  'cpp',
  'c++',
  'cxx',
  'cc',
  'h',
  'asp',
  'aspx',
  'php',
  'phpx',
  'jsp',
  'jspx',
  'vm',
  'go',
  'dart',
  'ts',
  'tsx',
  'hpp',
  'hxx',
  'sh',
  'cs',
  'py',
  'py3',
  'pl',
  'kt',
  'js',
  'jsx',
  'json',
  'html',
  'htm',
  'xhtml',
  'css',
  'less',
  'scss',
  'yml',
  'yaml',
  'sql',
];
